project:
  type: book
  output-dir: docs

book:
  title: "R and Health Sciences"
  site-url: https://annyrodriguez.github.io/mph716/
  author: "Anny D. Rodriguez, PhD, MPH"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-quarto.qmd
    - 02b-inline.qmd
    - 02c-review.qmd
    - 03-visualizations.qmd
    - 04-dplyr.qmd
    - project1.qmd
    - 05-tidydata.qmd
    - 06a-biostats1review.qmd
    - 06-slr.qmd
    - 07-mlr.qmd
    - project2.qmd
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: false



